services:
  - type: web
    name: decasa-api
    env: docker
    rootDir: decasa-api
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_TIMEZONE
        value: America/Bogota
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      - key: BROADCAST_CONNECTION
        value: pusher
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: warning
      - key: APP_URL
        value: https://decasa-api-b91v.onrender.com
      - key: SANCTUM_STATEFUL_DOMAINS
        value: sistema-de-ventas-olive.vercel.app
